### PR TITLE
Ban unsolicited advertising

### PR DESCRIPTION
**Pull request by nicklambourne**
Plz feedback

Adds a clause explicitly banning unsolicited advertising without the permission of the committee (with the exception of #jobs-bulletin).

### CODE REVIEW

**Comment by jdcaperon** [comment]
Good idea. 👍

**Comment by me4502** [comment]
Is it worth specifying advertisement of jobs/positions etc is banned, rather than just blanket banning advertisement?

This could come across to some as people aren't allowed to show off their projects in #projects, etc

**Comment by JamesDearlove** [comment]
I agree with @me4502 with this precedent set that people may feel they are unable to show off their projects. 

Is there a way that we can phrase it that projects created by members is allowed, and prohibiting joining our platforms for the sole purpose of advertising? Or alternatively, do we consider #general (and related general chat platforms) off limits for posting about projects and instead direct them to share them in #projects and the relevant channels?

**Comment by jdcaperon** [comment]
I would say that:

- Showing off != advertising
- #projects is solicited conversation about personal projects and hence not unsolicited

In reality, it's up to the committee to enforce this in a sensible/fair way, since the code of conduct is subject to the will of the committee :)

**Comment by me4502** [comment]
Yeah I'm not as much concerned that the committee will enforce it on projects, moreso that it may dissuade new members from showing off stuff they've made

**Comment by nicklambourne** [comment]
Something like this, perhaps?

> Unsolicited advertising is also prohibited on UQCS-managed platforms unless the express permission of the UQCS committee has been provided (as with the blanket permission extended to the #jobs-bulletin Slack channel). Such posts will be immediately removed and repeat offenders will be subject to the disciplinary procedures outlined above at the discretion of the committee. Note that sharing of personal projects is not considered advertising and is encouraged on appropriate platforms except in the case where those projects are of a commercial nature and are being shared with the intent to acquire customers.

**Comment by me4502** [comment]
Yeah something like that looks good IMO 👍

**Review by jdcaperon — APPROVED** [review]

**Comment by jdcaperon** [comment]
Although wait for @JamesDearlove to review, I _can't_ enforce it anymore ;)

**Comment by mattchrlw** [comment]
Thanks @nicklambourne for writing this one up. The committee has discretion over these kinds of things, but a clear rule in code of conduct regarding spam helps us take action without hesitation.

**Review by kentonlam — APPROVED** [review]
I agree with the discussion. If it helps, we could add examples of what is/isn't considered unsolicited advertising, but it's also fine as is.

**Review by JamesDearlove — APPROVED** [review]
I'm happy with the changes. Thanks everyone for their input around it

**Pull request merged**
